name: CI devops 2025

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  # 1. Build and test the Java backend
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: "TP2 - Github Actions/simpleapi/"

  # 2. Build and optionally push Docker images
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Build backend image
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: "TP2 - Github Actions/simpleapi/"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-simple:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build database image
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: "./path/to/your/db"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/db-simple:latest
          push: ${{ github.ref == 'refs/heads/main' }}
